"""Models

Revision ID: 2abd4d6c20af
Revises: 7496c04d7d5a
Create Date: 2023-12-20 17:02:11.306146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abd4d6c20af'
down_revision: Union[str, None] = '7496c04d7d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('dni', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('persona', sa.Column('is_gba', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_persona_date'), 'persona', ['date'], unique=True)
    op.create_index(op.f('ix_persona_dni'), 'persona', ['dni'], unique=True)
    op.create_index(op.f('ix_persona_is_gba'), 'persona', ['is_gba'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_is_gba'), table_name='persona')
    op.drop_index(op.f('ix_persona_dni'), table_name='persona')
    op.drop_index(op.f('ix_persona_date'), table_name='persona')
    op.drop_column('persona', 'is_gba')
    op.drop_column('persona', 'date')
    op.drop_column('persona', 'dni')
    # ### end Alembic commands ###
